module Spotted
  module Resources
    class Me
      class Playlists
        def retrieve: (
          ?limit: Integer,
          ?offset: Integer,
          ?request_options: Spotted::request_opts
        ) -> Spotted::PagingPlaylistObject

        def initialize: (client: Spotted::Client) -> void
      end
    end
  end
end
