module Spotted
  module Models
    type album_restriction_object =
      {
        published: bool,
        reason: Spotted::Models::AlbumRestrictionObject::reason
      }

    class AlbumRestrictionObject < Spotted::Internal::Type::BaseModel
      attr_reader published: bool?

      def published=: (bool) -> bool

      attr_reader reason: Spotted::Models::AlbumRestrictionObject::reason?

      def reason=: (
        Spotted::Models::AlbumRestrictionObject::reason
      ) -> Spotted::Models::AlbumRestrictionObject::reason

      def initialize: (
        ?published: bool,
        ?reason: Spotted::Models::AlbumRestrictionObject::reason
      ) -> void

      def to_hash: -> {
        published: bool,
        reason: Spotted::Models::AlbumRestrictionObject::reason
      }

      type reason = :market | :product | :explicit

      module Reason
        extend Spotted::Internal::Type::Enum

        MARKET: :market
        PRODUCT: :product
        EXPLICIT: :explicit

        def self?.values: -> ::Array[Spotted::Models::AlbumRestrictionObject::reason]
      end
    end
  end
end
