module Spotted
  module Models
    type audiobook_bulk_retrieve_response =
      {
        audiobooks: ::Array[Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook]
      }

    class AudiobookBulkRetrieveResponse < Spotted::Internal::Type::BaseModel
      attr_accessor audiobooks: ::Array[Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook]

      def initialize: (
        audiobooks: ::Array[Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook]
      ) -> void

      def to_hash: -> {
        audiobooks: ::Array[Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook]
      }

      type audiobook =
        {
          chapters: Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook::Chapters
        }

      class Audiobook < Spotted::Models::AudiobookBase
        def chapters: -> Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook::Chapters

        def chapters=: (
          Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook::Chapters _
        ) -> Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook::Chapters

        def initialize: (
          chapters: Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook::Chapters
        ) -> void

        def to_hash: -> {
          chapters: Spotted::Models::AudiobookBulkRetrieveResponse::Audiobook::Chapters
        }

        type chapters =
          {
            href: String,
            limit: Integer,
            next_: String?,
            offset: Integer,
            previous: String?,
            total: Integer,
            items: ::Array[Spotted::SimplifiedChapterObject]
          }

        class Chapters < Spotted::Internal::Type::BaseModel
          attr_accessor href: String

          attr_accessor limit: Integer

          attr_accessor next_: String?

          attr_accessor offset: Integer

          attr_accessor previous: String?

          attr_accessor total: Integer

          attr_reader items: ::Array[Spotted::SimplifiedChapterObject]?

          def items=: (
            ::Array[Spotted::SimplifiedChapterObject]
          ) -> ::Array[Spotted::SimplifiedChapterObject]

          def initialize: (
            href: String,
            limit: Integer,
            next_: String?,
            offset: Integer,
            previous: String?,
            total: Integer,
            ?items: ::Array[Spotted::SimplifiedChapterObject]
          ) -> void

          def to_hash: -> {
            href: String,
            limit: Integer,
            next_: String?,
            offset: Integer,
            previous: String?,
            total: Integer,
            items: ::Array[Spotted::SimplifiedChapterObject]
          }
        end
      end
    end
  end
end
