module Spotted
  module Models
    type audio_feature_retrieve_params =
      { id: String } & Spotted::Internal::Type::request_parameters

    class AudioFeatureRetrieveParams < Spotted::Internal::Type::BaseModel
      extend Spotted::Internal::Type::RequestParameters::Converter
      include Spotted::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: Spotted::request_opts
      ) -> void

      def to_hash: -> { id: String, request_options: Spotted::RequestOptions }
    end
  end
end
