module Spotted
  module Models
    type browse_get_featured_playlists_response =
      {
        message: String,
        playlists: Spotted::PagingPlaylistObject,
        published: bool
      }

    class BrowseGetFeaturedPlaylistsResponse < Spotted::Internal::Type::BaseModel
      attr_reader message: String?

      def message=: (String) -> String

      attr_reader playlists: Spotted::PagingPlaylistObject?

      def playlists=: (
        Spotted::PagingPlaylistObject
      ) -> Spotted::PagingPlaylistObject

      attr_reader published: bool?

      def published=: (bool) -> bool

      def initialize: (
        ?message: String,
        ?playlists: Spotted::PagingPlaylistObject,
        ?published: bool
      ) -> void

      def to_hash: -> {
        message: String,
        playlists: Spotted::PagingPlaylistObject,
        published: bool
      }
    end
  end
end
