module Spotted
  module Models
    type browse_get_featured_playlists_response =
      { message: String, playlists: Spotted::PagingPlaylistObject }

    class BrowseGetFeaturedPlaylistsResponse < Spotted::Internal::Type::BaseModel
      attr_reader message: String?

      def message=: (String) -> String

      attr_reader playlists: Spotted::PagingPlaylistObject?

      def playlists=: (
        Spotted::PagingPlaylistObject
      ) -> Spotted::PagingPlaylistObject

      def initialize: (
        ?message: String,
        ?playlists: Spotted::PagingPlaylistObject
      ) -> void

      def to_hash: -> {
        message: String,
        playlists: Spotted::PagingPlaylistObject
      }
    end
  end
end
