module Spotted
  module Models
    type chapter_restriction_object = { published: bool, reason: String }

    class ChapterRestrictionObject < Spotted::Internal::Type::BaseModel
      attr_reader published: bool?

      def published=: (bool) -> bool

      attr_reader reason: String?

      def reason=: (String) -> String

      def initialize: (?published: bool, ?reason: String) -> void

      def to_hash: -> { published: bool, reason: String }
    end
  end
end
