module Spotted
  module Models
    type copyright_object = { text: String, type: String }

    class CopyrightObject < Spotted::Internal::Type::BaseModel
      attr_reader text: String?

      def text=: (String) -> String

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (?text: String, ?type: String) -> void

      def to_hash: -> { text: String, type: String }
    end
  end
end
