module Spotted
  module Models
    type copyright_object = { published: bool, text: String, type: String }

    class CopyrightObject < Spotted::Internal::Type::BaseModel
      attr_reader published: bool?

      def published=: (bool) -> bool

      attr_reader text: String?

      def text=: (String) -> String

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (?published: bool, ?text: String, ?type: String) -> void

      def to_hash: -> { published: bool, text: String, type: String }
    end
  end
end
