module Spotted
  module Models
    type external_url_object = { published: bool, spotify: String }

    class ExternalURLObject < Spotted::Internal::Type::BaseModel
      attr_reader published: bool?

      def published=: (bool) -> bool

      attr_reader spotify: String?

      def spotify=: (String) -> String

      def initialize: (?published: bool, ?spotify: String) -> void

      def to_hash: -> { published: bool, spotify: String }
    end
  end
end
