module Spotted
  module Models
    type external_id_object =
      { ean: String, isrc: String, published: bool, upc: String }

    class ExternalIDObject < Spotted::Internal::Type::BaseModel
      attr_reader ean: String?

      def ean=: (String) -> String

      attr_reader isrc: String?

      def isrc=: (String) -> String

      attr_reader published: bool?

      def published=: (bool) -> bool

      attr_reader upc: String?

      def upc=: (String) -> String

      def initialize: (
        ?ean: String,
        ?isrc: String,
        ?published: bool,
        ?upc: String
      ) -> void

      def to_hash: -> {
        ean: String,
        isrc: String,
        published: bool,
        upc: String
      }
    end
  end
end
