module Spotted
  module Models
    type followers_object = { href: String?, total: Integer }

    class FollowersObject < Spotted::Internal::Type::BaseModel
      attr_accessor href: String?

      attr_reader total: Integer?

      def total=: (Integer) -> Integer

      def initialize: (?href: String?, ?total: Integer) -> void

      def to_hash: -> { href: String?, total: Integer }
    end
  end
end
