module Spotted
  module Models
    type followers_object = { href: String?, published: bool, total: Integer }

    class FollowersObject < Spotted::Internal::Type::BaseModel
      attr_accessor href: String?

      attr_reader published: bool?

      def published=: (bool) -> bool

      attr_reader total: Integer?

      def total=: (Integer) -> Integer

      def initialize: (
        ?href: String?,
        ?published: bool,
        ?total: Integer
      ) -> void

      def to_hash: -> { href: String?, published: bool, total: Integer }
    end
  end
end
