module Spotted
  module Models
    type image_object =
      { height: Integer?, url: String, width: Integer?, published: bool }

    class ImageObject < Spotted::Internal::Type::BaseModel
      attr_accessor height: Integer?

      attr_accessor url: String

      attr_accessor width: Integer?

      attr_reader published: bool?

      def published=: (bool) -> bool

      def initialize: (
        height: Integer?,
        url: String,
        width: Integer?,
        ?published: bool
      ) -> void

      def to_hash: -> {
        height: Integer?,
        url: String,
        width: Integer?,
        published: bool
      }
    end
  end
end
