module Spotted
  module Models
    type market_list_response = { markets: ::Array[String] }

    class MarketListResponse < Spotted::Internal::Type::BaseModel
      attr_reader markets: ::Array[String]?

      def markets=: (::Array[String]) -> ::Array[String]

      def initialize: (?markets: ::Array[String]) -> void

      def to_hash: -> { markets: ::Array[String] }
    end
  end
end
