module Spotted
  module Models
    type playlist_update_params =
      {
        playlist_id: String,
        collaborative: bool,
        description: String,
        name: String,
        published: bool
      }
      & Spotted::Internal::Type::request_parameters

    class PlaylistUpdateParams < Spotted::Internal::Type::BaseModel
      extend Spotted::Internal::Type::RequestParameters::Converter
      include Spotted::Internal::Type::RequestParameters

      attr_accessor playlist_id: String

      attr_reader collaborative: bool?

      def collaborative=: (bool) -> bool

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader published: bool?

      def published=: (bool) -> bool

      def initialize: (
        playlist_id: String,
        ?collaborative: bool,
        ?description: String,
        ?name: String,
        ?published: bool,
        ?request_options: Spotted::request_opts
      ) -> void

      def to_hash: -> {
        playlist_id: String,
        collaborative: bool,
        description: String,
        name: String,
        published: bool,
        request_options: Spotted::RequestOptions
      }
    end
  end
end
