module Spotted
  module Models
    type playlist_update_params =
      {
        paths_request_body_content_application_json_schema_properties_published: bool,
        collaborative: bool,
        description: String,
        name: String
      }
      & Spotted::Internal::Type::request_parameters

    class PlaylistUpdateParams < Spotted::Internal::Type::BaseModel
      extend Spotted::Internal::Type::RequestParameters::Converter
      include Spotted::Internal::Type::RequestParameters

      attr_reader paths_request_body_content_application_json_schema_properties_published: bool?

      def paths_request_body_content_application_json_schema_properties_published=: (
        bool
      ) -> bool

      attr_reader collaborative: bool?

      def collaborative=: (bool) -> bool

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        ?paths_request_body_content_application_json_schema_properties_published: bool,
        ?collaborative: bool,
        ?description: String,
        ?name: String,
        ?request_options: Spotted::request_opts
      ) -> void

      def to_hash: -> {
        paths_request_body_content_application_json_schema_properties_published: bool,
        collaborative: bool,
        description: String,
        name: String,
        request_options: Spotted::RequestOptions
      }
    end
  end
end
