module Spotted
  module Models
    type recommendation_list_available_genre_seeds_response =
      { genres: ::Array[String] }

    class RecommendationListAvailableGenreSeedsResponse < Spotted::Internal::Type::BaseModel
      attr_accessor genres: ::Array[String]

      def initialize: (genres: ::Array[String]) -> void

      def to_hash: -> { genres: ::Array[String] }
    end
  end
end
