module Spotted
  module Models
    type search_retrieve_response =
      {
        albums: Spotted::Models::SearchRetrieveResponse::Albums,
        artists: Spotted::Models::SearchRetrieveResponse::Artists,
        audiobooks: Spotted::Models::SearchRetrieveResponse::Audiobooks,
        episodes: Spotted::Models::SearchRetrieveResponse::Episodes,
        playlists: Spotted::PagingPlaylistObject,
        shows: Spotted::Models::SearchRetrieveResponse::Shows,
        tracks: Spotted::Models::SearchRetrieveResponse::Tracks
      }

    class SearchRetrieveResponse < Spotted::Internal::Type::BaseModel
      attr_reader albums: Spotted::Models::SearchRetrieveResponse::Albums?

      def albums=: (
        Spotted::Models::SearchRetrieveResponse::Albums
      ) -> Spotted::Models::SearchRetrieveResponse::Albums

      attr_reader artists: Spotted::Models::SearchRetrieveResponse::Artists?

      def artists=: (
        Spotted::Models::SearchRetrieveResponse::Artists
      ) -> Spotted::Models::SearchRetrieveResponse::Artists

      attr_reader audiobooks: Spotted::Models::SearchRetrieveResponse::Audiobooks?

      def audiobooks=: (
        Spotted::Models::SearchRetrieveResponse::Audiobooks
      ) -> Spotted::Models::SearchRetrieveResponse::Audiobooks

      attr_reader episodes: Spotted::Models::SearchRetrieveResponse::Episodes?

      def episodes=: (
        Spotted::Models::SearchRetrieveResponse::Episodes
      ) -> Spotted::Models::SearchRetrieveResponse::Episodes

      attr_reader playlists: Spotted::PagingPlaylistObject?

      def playlists=: (
        Spotted::PagingPlaylistObject
      ) -> Spotted::PagingPlaylistObject

      attr_reader shows: Spotted::Models::SearchRetrieveResponse::Shows?

      def shows=: (
        Spotted::Models::SearchRetrieveResponse::Shows
      ) -> Spotted::Models::SearchRetrieveResponse::Shows

      attr_reader tracks: Spotted::Models::SearchRetrieveResponse::Tracks?

      def tracks=: (
        Spotted::Models::SearchRetrieveResponse::Tracks
      ) -> Spotted::Models::SearchRetrieveResponse::Tracks

      def initialize: (
        ?albums: Spotted::Models::SearchRetrieveResponse::Albums,
        ?artists: Spotted::Models::SearchRetrieveResponse::Artists,
        ?audiobooks: Spotted::Models::SearchRetrieveResponse::Audiobooks,
        ?episodes: Spotted::Models::SearchRetrieveResponse::Episodes,
        ?playlists: Spotted::PagingPlaylistObject,
        ?shows: Spotted::Models::SearchRetrieveResponse::Shows,
        ?tracks: Spotted::Models::SearchRetrieveResponse::Tracks
      ) -> void

      def to_hash: -> {
        albums: Spotted::Models::SearchRetrieveResponse::Albums,
        artists: Spotted::Models::SearchRetrieveResponse::Artists,
        audiobooks: Spotted::Models::SearchRetrieveResponse::Audiobooks,
        episodes: Spotted::Models::SearchRetrieveResponse::Episodes,
        playlists: Spotted::PagingPlaylistObject,
        shows: Spotted::Models::SearchRetrieveResponse::Shows,
        tracks: Spotted::Models::SearchRetrieveResponse::Tracks
      }

      type albums =
        {
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Albums::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

      class Albums < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor items: ::Array[Spotted::Models::SearchRetrieveResponse::Albums::Item]

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        def initialize: (
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Albums::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        ) -> void

        def to_hash: -> {
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Albums::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

        type item =
          {
            id: String,
            album_type: Spotted::Models::SearchRetrieveResponse::Albums::Item::album_type,
            artists: ::Array[Spotted::SimplifiedArtistObject],
            available_markets: ::Array[String],
            external_urls: Spotted::ExternalURLObject,
            href: String,
            images: ::Array[Spotted::ImageObject],
            name: String,
            release_date: String,
            release_date_precision: Spotted::Models::SearchRetrieveResponse::Albums::Item::release_date_precision,
            total_tracks: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Albums::Item::type_,
            uri: String,
            restrictions: Spotted::AlbumRestrictionObject
          }

        class Item < Spotted::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor album_type: Spotted::Models::SearchRetrieveResponse::Albums::Item::album_type

          attr_accessor artists: ::Array[Spotted::SimplifiedArtistObject]

          attr_accessor available_markets: ::Array[String]

          attr_accessor external_urls: Spotted::ExternalURLObject

          attr_accessor href: String

          attr_accessor images: ::Array[Spotted::ImageObject]

          attr_accessor name: String

          attr_accessor release_date: String

          attr_accessor release_date_precision: Spotted::Models::SearchRetrieveResponse::Albums::Item::release_date_precision

          attr_accessor total_tracks: Integer

          attr_accessor type: Spotted::Models::SearchRetrieveResponse::Albums::Item::type_

          attr_accessor uri: String

          attr_reader restrictions: Spotted::AlbumRestrictionObject?

          def restrictions=: (
            Spotted::AlbumRestrictionObject
          ) -> Spotted::AlbumRestrictionObject

          def initialize: (
            id: String,
            album_type: Spotted::Models::SearchRetrieveResponse::Albums::Item::album_type,
            artists: ::Array[Spotted::SimplifiedArtistObject],
            available_markets: ::Array[String],
            external_urls: Spotted::ExternalURLObject,
            href: String,
            images: ::Array[Spotted::ImageObject],
            name: String,
            release_date: String,
            release_date_precision: Spotted::Models::SearchRetrieveResponse::Albums::Item::release_date_precision,
            total_tracks: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Albums::Item::type_,
            uri: String,
            ?restrictions: Spotted::AlbumRestrictionObject
          ) -> void

          def to_hash: -> {
            id: String,
            album_type: Spotted::Models::SearchRetrieveResponse::Albums::Item::album_type,
            artists: ::Array[Spotted::SimplifiedArtistObject],
            available_markets: ::Array[String],
            external_urls: Spotted::ExternalURLObject,
            href: String,
            images: ::Array[Spotted::ImageObject],
            name: String,
            release_date: String,
            release_date_precision: Spotted::Models::SearchRetrieveResponse::Albums::Item::release_date_precision,
            total_tracks: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Albums::Item::type_,
            uri: String,
            restrictions: Spotted::AlbumRestrictionObject
          }

          type album_type = :album | :single | :compilation

          module AlbumType
            extend Spotted::Internal::Type::Enum

            ALBUM: :album
            SINGLE: :single
            COMPILATION: :compilation

            def self?.values: -> ::Array[Spotted::Models::SearchRetrieveResponse::Albums::Item::album_type]
          end

          type release_date_precision = :year | :month | :day

          module ReleaseDatePrecision
            extend Spotted::Internal::Type::Enum

            YEAR: :year
            MONTH: :month
            DAY: :day

            def self?.values: -> ::Array[Spotted::Models::SearchRetrieveResponse::Albums::Item::release_date_precision]
          end

          type type_ = :album

          module Type
            extend Spotted::Internal::Type::Enum

            ALBUM: :album

            def self?.values: -> ::Array[Spotted::Models::SearchRetrieveResponse::Albums::Item::type_]
          end
        end
      end

      type artists =
        {
          href: String,
          items: ::Array[Spotted::ArtistObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

      class Artists < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor items: ::Array[Spotted::ArtistObject]

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        def initialize: (
          href: String,
          items: ::Array[Spotted::ArtistObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        ) -> void

        def to_hash: -> {
          href: String,
          items: ::Array[Spotted::ArtistObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }
      end

      type audiobooks =
        {
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Audiobooks::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

      class Audiobooks < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor items: ::Array[Spotted::Models::SearchRetrieveResponse::Audiobooks::Item]

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        def initialize: (
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Audiobooks::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        ) -> void

        def to_hash: -> {
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Audiobooks::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

        type item =
          {
            id: String,
            authors: ::Array[Spotted::AuthorObject],
            available_markets: ::Array[String],
            copyrights: ::Array[Spotted::CopyrightObject],
            description: String,
            explicit: bool,
            external_urls: Spotted::ExternalURLObject,
            href: String,
            html_description: String,
            images: ::Array[Spotted::ImageObject],
            languages: ::Array[String],
            media_type: String,
            name: String,
            narrators: ::Array[Spotted::NarratorObject],
            publisher: String,
            total_chapters: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Audiobooks::Item::type_,
            uri: String,
            edition: String
          }

        class Item < Spotted::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor authors: ::Array[Spotted::AuthorObject]

          attr_accessor available_markets: ::Array[String]

          attr_accessor copyrights: ::Array[Spotted::CopyrightObject]

          attr_accessor description: String

          attr_accessor explicit: bool

          attr_accessor external_urls: Spotted::ExternalURLObject

          attr_accessor href: String

          attr_accessor html_description: String

          attr_accessor images: ::Array[Spotted::ImageObject]

          attr_accessor languages: ::Array[String]

          attr_accessor media_type: String

          attr_accessor name: String

          attr_accessor narrators: ::Array[Spotted::NarratorObject]

          attr_accessor publisher: String

          attr_accessor total_chapters: Integer

          attr_accessor type: Spotted::Models::SearchRetrieveResponse::Audiobooks::Item::type_

          attr_accessor uri: String

          attr_reader edition: String?

          def edition=: (String) -> String

          def initialize: (
            id: String,
            authors: ::Array[Spotted::AuthorObject],
            available_markets: ::Array[String],
            copyrights: ::Array[Spotted::CopyrightObject],
            description: String,
            explicit: bool,
            external_urls: Spotted::ExternalURLObject,
            href: String,
            html_description: String,
            images: ::Array[Spotted::ImageObject],
            languages: ::Array[String],
            media_type: String,
            name: String,
            narrators: ::Array[Spotted::NarratorObject],
            publisher: String,
            total_chapters: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Audiobooks::Item::type_,
            uri: String,
            ?edition: String
          ) -> void

          def to_hash: -> {
            id: String,
            authors: ::Array[Spotted::AuthorObject],
            available_markets: ::Array[String],
            copyrights: ::Array[Spotted::CopyrightObject],
            description: String,
            explicit: bool,
            external_urls: Spotted::ExternalURLObject,
            href: String,
            html_description: String,
            images: ::Array[Spotted::ImageObject],
            languages: ::Array[String],
            media_type: String,
            name: String,
            narrators: ::Array[Spotted::NarratorObject],
            publisher: String,
            total_chapters: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Audiobooks::Item::type_,
            uri: String,
            edition: String
          }

          type type_ = :audiobook

          module Type
            extend Spotted::Internal::Type::Enum

            AUDIOBOOK: :audiobook

            def self?.values: -> ::Array[Spotted::Models::SearchRetrieveResponse::Audiobooks::Item::type_]
          end
        end
      end

      type episodes =
        {
          href: String,
          items: ::Array[Spotted::SimplifiedEpisodeObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

      class Episodes < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor items: ::Array[Spotted::SimplifiedEpisodeObject]

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        def initialize: (
          href: String,
          items: ::Array[Spotted::SimplifiedEpisodeObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        ) -> void

        def to_hash: -> {
          href: String,
          items: ::Array[Spotted::SimplifiedEpisodeObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }
      end

      type shows =
        {
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Shows::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

      class Shows < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor items: ::Array[Spotted::Models::SearchRetrieveResponse::Shows::Item]

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        def initialize: (
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Shows::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        ) -> void

        def to_hash: -> {
          href: String,
          items: ::Array[Spotted::Models::SearchRetrieveResponse::Shows::Item],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

        type item =
          {
            id: String,
            available_markets: ::Array[String],
            copyrights: ::Array[Spotted::CopyrightObject],
            description: String,
            explicit: bool,
            external_urls: Spotted::ExternalURLObject,
            href: String,
            html_description: String,
            images: ::Array[Spotted::ImageObject],
            is_externally_hosted: bool,
            languages: ::Array[String],
            media_type: String,
            name: String,
            publisher: String,
            total_episodes: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Shows::Item::type_,
            uri: String
          }

        class Item < Spotted::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor available_markets: ::Array[String]

          attr_accessor copyrights: ::Array[Spotted::CopyrightObject]

          attr_accessor description: String

          attr_accessor explicit: bool

          attr_accessor external_urls: Spotted::ExternalURLObject

          attr_accessor href: String

          attr_accessor html_description: String

          attr_accessor images: ::Array[Spotted::ImageObject]

          attr_accessor is_externally_hosted: bool

          attr_accessor languages: ::Array[String]

          attr_accessor media_type: String

          attr_accessor name: String

          attr_accessor publisher: String

          attr_accessor total_episodes: Integer

          attr_accessor type: Spotted::Models::SearchRetrieveResponse::Shows::Item::type_

          attr_accessor uri: String

          def initialize: (
            id: String,
            available_markets: ::Array[String],
            copyrights: ::Array[Spotted::CopyrightObject],
            description: String,
            explicit: bool,
            external_urls: Spotted::ExternalURLObject,
            href: String,
            html_description: String,
            images: ::Array[Spotted::ImageObject],
            is_externally_hosted: bool,
            languages: ::Array[String],
            media_type: String,
            name: String,
            publisher: String,
            total_episodes: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Shows::Item::type_,
            uri: String
          ) -> void

          def to_hash: -> {
            id: String,
            available_markets: ::Array[String],
            copyrights: ::Array[Spotted::CopyrightObject],
            description: String,
            explicit: bool,
            external_urls: Spotted::ExternalURLObject,
            href: String,
            html_description: String,
            images: ::Array[Spotted::ImageObject],
            is_externally_hosted: bool,
            languages: ::Array[String],
            media_type: String,
            name: String,
            publisher: String,
            total_episodes: Integer,
            type: Spotted::Models::SearchRetrieveResponse::Shows::Item::type_,
            uri: String
          }

          type type_ = :show

          module Type
            extend Spotted::Internal::Type::Enum

            SHOW: :show

            def self?.values: -> ::Array[Spotted::Models::SearchRetrieveResponse::Shows::Item::type_]
          end
        end
      end

      type tracks =
        {
          href: String,
          items: ::Array[Spotted::TrackObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }

      class Tracks < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor items: ::Array[Spotted::TrackObject]

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        def initialize: (
          href: String,
          items: ::Array[Spotted::TrackObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        ) -> void

        def to_hash: -> {
          href: String,
          items: ::Array[Spotted::TrackObject],
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer
        }
      end
    end
  end
end
