module Spotted
  module Models
    type search_retrieve_params =
      {
        q: String,
        type: ::Array[Spotted::Models::SearchRetrieveParams::type_],
        include_external: Spotted::Models::SearchRetrieveParams::include_external,
        limit: Integer,
        market: String,
        offset: Integer
      }
      & Spotted::Internal::Type::request_parameters

    class SearchRetrieveParams < Spotted::Internal::Type::BaseModel
      extend Spotted::Internal::Type::RequestParameters::Converter
      include Spotted::Internal::Type::RequestParameters

      attr_accessor q: String

      attr_accessor type: ::Array[Spotted::Models::SearchRetrieveParams::type_]

      attr_reader include_external: Spotted::Models::SearchRetrieveParams::include_external?

      def include_external=: (
        Spotted::Models::SearchRetrieveParams::include_external
      ) -> Spotted::Models::SearchRetrieveParams::include_external

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader market: String?

      def market=: (String) -> String

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      def initialize: (
        q: String,
        type: ::Array[Spotted::Models::SearchRetrieveParams::type_],
        ?include_external: Spotted::Models::SearchRetrieveParams::include_external,
        ?limit: Integer,
        ?market: String,
        ?offset: Integer,
        ?request_options: Spotted::request_opts
      ) -> void

      def to_hash: -> {
        q: String,
        type: ::Array[Spotted::Models::SearchRetrieveParams::type_],
        include_external: Spotted::Models::SearchRetrieveParams::include_external,
        limit: Integer,
        market: String,
        offset: Integer,
        request_options: Spotted::RequestOptions
      }

      type type_ =
        :album | :artist | :playlist | :track | :show | :episode | :audiobook

      module Type
        extend Spotted::Internal::Type::Enum

        ALBUM: :album
        ARTIST: :artist
        PLAYLIST: :playlist
        TRACK: :track
        SHOW: :show
        EPISODE: :episode
        AUDIOBOOK: :audiobook

        def self?.values: -> ::Array[Spotted::Models::SearchRetrieveParams::type_]
      end

      type include_external = :audio

      module IncludeExternal
        extend Spotted::Internal::Type::Enum

        AUDIO: :audio

        def self?.values: -> ::Array[Spotted::Models::SearchRetrieveParams::include_external]
      end
    end
  end
end
