module Spotted
  module Models
    type search_query_response =
      {
        albums: Spotted::Models::SearchQueryResponse::Albums,
        artists: Spotted::Models::SearchQueryResponse::Artists,
        audiobooks: Spotted::Models::SearchQueryResponse::Audiobooks,
        episodes: Spotted::Models::SearchQueryResponse::Episodes,
        playlists: Spotted::PagingPlaylistObject,
        shows: Spotted::Models::SearchQueryResponse::Shows,
        tracks: Spotted::Models::SearchQueryResponse::Tracks
      }

    class SearchQueryResponse < Spotted::Internal::Type::BaseModel
      attr_reader albums: Spotted::Models::SearchQueryResponse::Albums?

      def albums=: (
        Spotted::Models::SearchQueryResponse::Albums
      ) -> Spotted::Models::SearchQueryResponse::Albums

      attr_reader artists: Spotted::Models::SearchQueryResponse::Artists?

      def artists=: (
        Spotted::Models::SearchQueryResponse::Artists
      ) -> Spotted::Models::SearchQueryResponse::Artists

      attr_reader audiobooks: Spotted::Models::SearchQueryResponse::Audiobooks?

      def audiobooks=: (
        Spotted::Models::SearchQueryResponse::Audiobooks
      ) -> Spotted::Models::SearchQueryResponse::Audiobooks

      attr_reader episodes: Spotted::Models::SearchQueryResponse::Episodes?

      def episodes=: (
        Spotted::Models::SearchQueryResponse::Episodes
      ) -> Spotted::Models::SearchQueryResponse::Episodes

      attr_reader playlists: Spotted::PagingPlaylistObject?

      def playlists=: (
        Spotted::PagingPlaylistObject
      ) -> Spotted::PagingPlaylistObject

      attr_reader shows: Spotted::Models::SearchQueryResponse::Shows?

      def shows=: (
        Spotted::Models::SearchQueryResponse::Shows
      ) -> Spotted::Models::SearchQueryResponse::Shows

      attr_reader tracks: Spotted::Models::SearchQueryResponse::Tracks?

      def tracks=: (
        Spotted::Models::SearchQueryResponse::Tracks
      ) -> Spotted::Models::SearchQueryResponse::Tracks

      def initialize: (
        ?albums: Spotted::Models::SearchQueryResponse::Albums,
        ?artists: Spotted::Models::SearchQueryResponse::Artists,
        ?audiobooks: Spotted::Models::SearchQueryResponse::Audiobooks,
        ?episodes: Spotted::Models::SearchQueryResponse::Episodes,
        ?playlists: Spotted::PagingPlaylistObject,
        ?shows: Spotted::Models::SearchQueryResponse::Shows,
        ?tracks: Spotted::Models::SearchQueryResponse::Tracks
      ) -> void

      def to_hash: -> {
        albums: Spotted::Models::SearchQueryResponse::Albums,
        artists: Spotted::Models::SearchQueryResponse::Artists,
        audiobooks: Spotted::Models::SearchQueryResponse::Audiobooks,
        episodes: Spotted::Models::SearchQueryResponse::Episodes,
        playlists: Spotted::PagingPlaylistObject,
        shows: Spotted::Models::SearchQueryResponse::Shows,
        tracks: Spotted::Models::SearchQueryResponse::Tracks
      }

      type albums =
        {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::Models::SearchQueryResponse::Albums::Item],
          published: bool
        }

      class Albums < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        attr_reader items: ::Array[Spotted::Models::SearchQueryResponse::Albums::Item]?

        def items=: (
          ::Array[Spotted::Models::SearchQueryResponse::Albums::Item]
        ) -> ::Array[Spotted::Models::SearchQueryResponse::Albums::Item]

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          ?items: ::Array[Spotted::Models::SearchQueryResponse::Albums::Item],
          ?published: bool
        ) -> void

        def to_hash: -> {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::Models::SearchQueryResponse::Albums::Item],
          published: bool
        }

        type item =
          {
            id: String,
            album_type: Spotted::Models::SearchQueryResponse::Albums::Item::album_type,
            artists: ::Array[Spotted::SimplifiedArtistObject],
            available_markets: ::Array[String],
            external_urls: Spotted::ExternalURLObject,
            href: String,
            images: ::Array[Spotted::ImageObject],
            name: String,
            release_date: String,
            release_date_precision: Spotted::Models::SearchQueryResponse::Albums::Item::release_date_precision,
            total_tracks: Integer,
            type: :album,
            uri: String,
            published: bool,
            restrictions: Spotted::AlbumRestrictionObject
          }

        class Item < Spotted::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor album_type: Spotted::Models::SearchQueryResponse::Albums::Item::album_type

          attr_accessor artists: ::Array[Spotted::SimplifiedArtistObject]

          attr_accessor available_markets: ::Array[String]

          attr_accessor external_urls: Spotted::ExternalURLObject

          attr_accessor href: String

          attr_accessor images: ::Array[Spotted::ImageObject]

          attr_accessor name: String

          attr_accessor release_date: String

          attr_accessor release_date_precision: Spotted::Models::SearchQueryResponse::Albums::Item::release_date_precision

          attr_accessor total_tracks: Integer

          attr_accessor type: :album

          attr_accessor uri: String

          attr_reader published: bool?

          def published=: (bool) -> bool

          attr_reader restrictions: Spotted::AlbumRestrictionObject?

          def restrictions=: (
            Spotted::AlbumRestrictionObject
          ) -> Spotted::AlbumRestrictionObject

          def initialize: (
            id: String,
            album_type: Spotted::Models::SearchQueryResponse::Albums::Item::album_type,
            artists: ::Array[Spotted::SimplifiedArtistObject],
            available_markets: ::Array[String],
            external_urls: Spotted::ExternalURLObject,
            href: String,
            images: ::Array[Spotted::ImageObject],
            name: String,
            release_date: String,
            release_date_precision: Spotted::Models::SearchQueryResponse::Albums::Item::release_date_precision,
            total_tracks: Integer,
            uri: String,
            ?published: bool,
            ?restrictions: Spotted::AlbumRestrictionObject,
            ?type: :album
          ) -> void

          def to_hash: -> {
            id: String,
            album_type: Spotted::Models::SearchQueryResponse::Albums::Item::album_type,
            artists: ::Array[Spotted::SimplifiedArtistObject],
            available_markets: ::Array[String],
            external_urls: Spotted::ExternalURLObject,
            href: String,
            images: ::Array[Spotted::ImageObject],
            name: String,
            release_date: String,
            release_date_precision: Spotted::Models::SearchQueryResponse::Albums::Item::release_date_precision,
            total_tracks: Integer,
            type: :album,
            uri: String,
            published: bool,
            restrictions: Spotted::AlbumRestrictionObject
          }

          type album_type = :album | :single | :compilation

          module AlbumType
            extend Spotted::Internal::Type::Enum

            ALBUM: :album
            SINGLE: :single
            COMPILATION: :compilation

            def self?.values: -> ::Array[Spotted::Models::SearchQueryResponse::Albums::Item::album_type]
          end

          type release_date_precision = :year | :month | :day

          module ReleaseDatePrecision
            extend Spotted::Internal::Type::Enum

            YEAR: :year
            MONTH: :month
            DAY: :day

            def self?.values: -> ::Array[Spotted::Models::SearchQueryResponse::Albums::Item::release_date_precision]
          end
        end
      end

      type artists =
        {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::ArtistObject],
          published: bool
        }

      class Artists < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        attr_reader items: ::Array[Spotted::ArtistObject]?

        def items=: (
          ::Array[Spotted::ArtistObject]
        ) -> ::Array[Spotted::ArtistObject]

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          ?items: ::Array[Spotted::ArtistObject],
          ?published: bool
        ) -> void

        def to_hash: -> {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::ArtistObject],
          published: bool
        }
      end

      type audiobooks =
        {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::AudiobookBase],
          published: bool
        }

      class Audiobooks < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        attr_reader items: ::Array[Spotted::AudiobookBase]?

        def items=: (
          ::Array[Spotted::AudiobookBase]
        ) -> ::Array[Spotted::AudiobookBase]

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          ?items: ::Array[Spotted::AudiobookBase],
          ?published: bool
        ) -> void

        def to_hash: -> {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::AudiobookBase],
          published: bool
        }
      end

      type episodes =
        {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::SimplifiedEpisodeObject],
          published: bool
        }

      class Episodes < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        attr_reader items: ::Array[Spotted::SimplifiedEpisodeObject]?

        def items=: (
          ::Array[Spotted::SimplifiedEpisodeObject]
        ) -> ::Array[Spotted::SimplifiedEpisodeObject]

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          ?items: ::Array[Spotted::SimplifiedEpisodeObject],
          ?published: bool
        ) -> void

        def to_hash: -> {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::SimplifiedEpisodeObject],
          published: bool
        }
      end

      type shows =
        {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::ShowBase],
          published: bool
        }

      class Shows < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        attr_reader items: ::Array[Spotted::ShowBase]?

        def items=: (::Array[Spotted::ShowBase]) -> ::Array[Spotted::ShowBase]

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          ?items: ::Array[Spotted::ShowBase],
          ?published: bool
        ) -> void

        def to_hash: -> {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::ShowBase],
          published: bool
        }
      end

      type tracks =
        {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::TrackObject],
          published: bool
        }

      class Tracks < Spotted::Internal::Type::BaseModel
        attr_accessor href: String

        attr_accessor limit: Integer

        attr_accessor next_: String?

        attr_accessor offset: Integer

        attr_accessor previous: String?

        attr_accessor total: Integer

        attr_reader items: ::Array[Spotted::TrackObject]?

        def items=: (
          ::Array[Spotted::TrackObject]
        ) -> ::Array[Spotted::TrackObject]

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          ?items: ::Array[Spotted::TrackObject],
          ?published: bool
        ) -> void

        def to_hash: -> {
          href: String,
          limit: Integer,
          next_: String?,
          offset: Integer,
          previous: String?,
          total: Integer,
          items: ::Array[Spotted::TrackObject],
          published: bool
        }
      end
    end
  end
end
