module Spotted
  module Models
    type show_list_response = { shows: ::Array[Spotted::ShowBase] }

    class ShowListResponse < Spotted::Internal::Type::BaseModel
      attr_accessor shows: ::Array[Spotted::ShowBase]

      def initialize: (shows: ::Array[Spotted::ShowBase]) -> void

      def to_hash: -> { shows: ::Array[Spotted::ShowBase] }
    end
  end
end
