module Spotted
  module Models
    type show_base =
      {
        id: String,
        available_markets: ::Array[String],
        copyrights: ::Array[Spotted::CopyrightObject],
        description: String,
        explicit: bool,
        external_urls: Spotted::ExternalURLObject,
        href: String,
        html_description: String,
        images: ::Array[Spotted::ImageObject],
        is_externally_hosted: bool,
        languages: ::Array[String],
        media_type: String,
        name: String,
        publisher: String,
        total_episodes: Integer,
        type: :show,
        uri: String
      }

    class ShowBase < Spotted::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor available_markets: ::Array[String]

      attr_accessor copyrights: ::Array[Spotted::CopyrightObject]

      attr_accessor description: String

      attr_accessor explicit: bool

      attr_accessor external_urls: Spotted::ExternalURLObject

      attr_accessor href: String

      attr_accessor html_description: String

      attr_accessor images: ::Array[Spotted::ImageObject]

      attr_accessor is_externally_hosted: bool

      attr_accessor languages: ::Array[String]

      attr_accessor media_type: String

      attr_accessor name: String

      attr_accessor publisher: String

      attr_accessor total_episodes: Integer

      attr_accessor type: :show

      attr_accessor uri: String

      def initialize: (
        id: String,
        available_markets: ::Array[String],
        copyrights: ::Array[Spotted::CopyrightObject],
        description: String,
        explicit: bool,
        external_urls: Spotted::ExternalURLObject,
        href: String,
        html_description: String,
        images: ::Array[Spotted::ImageObject],
        is_externally_hosted: bool,
        languages: ::Array[String],
        media_type: String,
        name: String,
        publisher: String,
        total_episodes: Integer,
        uri: String,
        ?type: :show
      ) -> void

      def to_hash: -> {
        id: String,
        available_markets: ::Array[String],
        copyrights: ::Array[Spotted::CopyrightObject],
        description: String,
        explicit: bool,
        external_urls: Spotted::ExternalURLObject,
        href: String,
        html_description: String,
        images: ::Array[Spotted::ImageObject],
        is_externally_hosted: bool,
        languages: ::Array[String],
        media_type: String,
        name: String,
        publisher: String,
        total_episodes: Integer,
        type: :show,
        uri: String
      }
    end
  end
end
