module Spotted
  module Models
    type time_interval_object =
      { confidence: Float, duration: Float, published: bool, start: Float }

    class TimeIntervalObject < Spotted::Internal::Type::BaseModel
      attr_reader confidence: Float?

      def confidence=: (Float) -> Float

      attr_reader duration: Float?

      def duration=: (Float) -> Float

      attr_reader published: bool?

      def published=: (bool) -> bool

      attr_reader start: Float?

      def start=: (Float) -> Float

      def initialize: (
        ?confidence: Float,
        ?duration: Float,
        ?published: bool,
        ?start: Float
      ) -> void

      def to_hash: -> {
        confidence: Float,
        duration: Float,
        published: bool,
        start: Float
      }
    end
  end
end
