module Spotted
  module Models
    type track_list_response = { tracks: ::Array[Spotted::TrackObject] }

    class TrackListResponse < Spotted::Internal::Type::BaseModel
      attr_accessor tracks: ::Array[Spotted::TrackObject]

      def initialize: (tracks: ::Array[Spotted::TrackObject]) -> void

      def to_hash: -> { tracks: ::Array[Spotted::TrackObject] }
    end
  end
end
