module Spotted
  module Models
    type user_retrieve_profile_response =
      {
        id: String,
        display_name: String?,
        external_urls: Spotted::ExternalURLObject,
        followers: Spotted::FollowersObject,
        href: String,
        images: ::Array[Spotted::ImageObject],
        type: Spotted::Models::UserRetrieveProfileResponse::type_,
        uri: String
      }

    class UserRetrieveProfileResponse < Spotted::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_accessor display_name: String?

      attr_reader external_urls: Spotted::ExternalURLObject?

      def external_urls=: (
        Spotted::ExternalURLObject
      ) -> Spotted::ExternalURLObject

      attr_reader followers: Spotted::FollowersObject?

      def followers=: (Spotted::FollowersObject) -> Spotted::FollowersObject

      attr_reader href: String?

      def href=: (String) -> String

      attr_reader images: ::Array[Spotted::ImageObject]?

      def images=: (
        ::Array[Spotted::ImageObject]
      ) -> ::Array[Spotted::ImageObject]

      attr_reader type: Spotted::Models::UserRetrieveProfileResponse::type_?

      def type=: (
        Spotted::Models::UserRetrieveProfileResponse::type_
      ) -> Spotted::Models::UserRetrieveProfileResponse::type_

      attr_reader uri: String?

      def uri=: (String) -> String

      def initialize: (
        ?id: String,
        ?display_name: String?,
        ?external_urls: Spotted::ExternalURLObject,
        ?followers: Spotted::FollowersObject,
        ?href: String,
        ?images: ::Array[Spotted::ImageObject],
        ?type: Spotted::Models::UserRetrieveProfileResponse::type_,
        ?uri: String
      ) -> void

      def to_hash: -> {
        id: String,
        display_name: String?,
        external_urls: Spotted::ExternalURLObject,
        followers: Spotted::FollowersObject,
        href: String,
        images: ::Array[Spotted::ImageObject],
        type: Spotted::Models::UserRetrieveProfileResponse::type_,
        uri: String
      }

      type type_ = :user

      module Type
        extend Spotted::Internal::Type::Enum

        USER: :user

        def self?.values: -> ::Array[Spotted::Models::UserRetrieveProfileResponse::type_]
      end
    end
  end
end
