module Spotted
  module Models
    type user_retrieve_profile_params =
      { user_id: String } & Spotted::Internal::Type::request_parameters

    class UserRetrieveProfileParams < Spotted::Internal::Type::BaseModel
      extend Spotted::Internal::Type::RequestParameters::Converter
      include Spotted::Internal::Type::RequestParameters

      attr_accessor user_id: String

      def initialize: (
        user_id: String,
        ?request_options: Spotted::request_opts
      ) -> void

      def to_hash: -> {
        user_id: String,
        request_options: Spotted::RequestOptions
      }
    end
  end
end
