module Spotted
  module Models
    module Me
      type following_bulk_retrieve_params =
        { type: :artist, after: String, limit: Integer }
        & Spotted::Internal::Type::request_parameters

      class FollowingBulkRetrieveParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_accessor type: :artist

        attr_reader after: String?

        def after=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          ?after: String,
          ?limit: Integer,
          ?type: :artist,
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          type: :artist,
          after: String,
          limit: Integer,
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
