module Spotted
  module Models
    module Me
      type player_toggle_shuffle_params =
        { state: bool, device_id: String }
        & Spotted::Internal::Type::request_parameters

      class PlayerToggleShuffleParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_accessor state: bool

        attr_reader device_id: String?

        def device_id=: (String) -> String

        def initialize: (
          state: bool,
          ?device_id: String,
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          state: bool,
          device_id: String,
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
