module Spotted
  module Models
    module Me
      type player_seek_to_position_params =
        { position_ms: Integer, device_id: String }
        & Spotted::Internal::Type::request_parameters

      class PlayerSeekToPositionParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_accessor position_ms: Integer

        attr_reader device_id: String?

        def device_id=: (String) -> String

        def initialize: (
          position_ms: Integer,
          ?device_id: String,
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          position_ms: Integer,
          device_id: String,
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
