module Spotted
  module Models
    module Me
      type player_set_volume_params =
        { volume_percent: Integer, device_id: String }
        & Spotted::Internal::Type::request_parameters

      class PlayerSetVolumeParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_accessor volume_percent: Integer

        attr_reader device_id: String?

        def device_id=: (String) -> String

        def initialize: (
          volume_percent: Integer,
          ?device_id: String,
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          volume_percent: Integer,
          device_id: String,
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
