module Spotted
  module Models
    module Me
      type player_get_devices_response =
        { devices: ::Array[Spotted::Me::DeviceObject] }

      class PlayerGetDevicesResponse < Spotted::Internal::Type::BaseModel
        attr_accessor devices: ::Array[Spotted::Me::DeviceObject]

        def initialize: (devices: ::Array[Spotted::Me::DeviceObject]) -> void

        def to_hash: -> { devices: ::Array[Spotted::Me::DeviceObject] }
      end
    end
  end
end
