module Spotted
  module Models
    module Me
      type top_list_response = Spotted::ArtistObject | Spotted::TrackObject

      module TopListResponse
        extend Spotted::Internal::Type::Union

        def self?.variants: -> ::Array[Spotted::Models::Me::top_list_response]
      end
    end
  end
end
