configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/testspotify%2Fspotted-623acfb611acabe3caa353e45c8faee0347dd7971e16b1d7c7277c579edb63bb.yml
openapi_spec_hash: cc60580d1dc62d9043850a9ca2fff6e1
config_hash: 2bb4e1a837ee50ac00a1ecf1d7f7e489
