module Spotted
  class AlbumRestrictionObject = Spotted::Models::AlbumRestrictionObject

  class AlbumRetrieveParams = Spotted::Models::AlbumRetrieveParams

  class ArtistObject = Spotted::Models::ArtistObject

  class AuthorObject = Spotted::Models::AuthorObject

  class ChapterRestrictionObject = Spotted::Models::ChapterRestrictionObject

  class CopyrightObject = Spotted::Models::CopyrightObject

  class EpisodeObject = Spotted::Models::EpisodeObject

  class EpisodeRestrictionObject = Spotted::Models::EpisodeRestrictionObject

  class ExternalIDObject = Spotted::Models::ExternalIDObject

  class ExternalURLObject = Spotted::Models::ExternalURLObject

  class FollowersObject = Spotted::Models::FollowersObject

  class ImageObject = Spotted::Models::ImageObject

  class LinkedTrackObject = Spotted::Models::LinkedTrackObject

  class NarratorObject = Spotted::Models::NarratorObject

  class PagingPlaylistObject = Spotted::Models::PagingPlaylistObject

  class PlaylistTrackObject = Spotted::Models::PlaylistTrackObject

  class PlaylistTracksRefObject = Spotted::Models::PlaylistTracksRefObject

  class PlaylistUserObject = Spotted::Models::PlaylistUserObject

  class ResumePointObject = Spotted::Models::ResumePointObject

  class SimplifiedArtistObject = Spotted::Models::SimplifiedArtistObject

  class SimplifiedEpisodeObject = Spotted::Models::SimplifiedEpisodeObject

  class SimplifiedPlaylistObject = Spotted::Models::SimplifiedPlaylistObject

  class SimplifiedTrackObject = Spotted::Models::SimplifiedTrackObject

  class TrackObject = Spotted::Models::TrackObject

  class TrackRestrictionObject = Spotted::Models::TrackRestrictionObject
end
