module Spotted
  module Resources
    class Albums
      def retrieve: (
        String id,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::AlbumRetrieveResponse

      def list: (
        ids: String,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::AlbumListResponse

      def initialize: (client: Spotted::Client) -> void
    end
  end
end
