module Spotted
  module Resources
    class Artists
      def retrieve: (
        String id,
        ?request_options: Spotted::request_opts
      ) -> Spotted::ArtistObject

      def list: (
        ids: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ArtistListResponse

      def list_albums: (
        String id,
        ?include_groups: String,
        ?limit: Integer,
        ?market: String,
        ?offset: Integer,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ArtistListAlbumsResponse

      def list_related_artists: (
        String id,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ArtistListRelatedArtistsResponse

      def list_top_tracks: (
        String id,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ArtistListTopTracksResponse

      def initialize: (client: Spotted::Client) -> void
    end
  end
end
