module Spotted
  module Resources
    class Artists
      def retrieve: (
        String id,
        ?request_options: Spotted::request_opts
      ) -> Spotted::ArtistObject

      def bulk_retrieve: (
        ids: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ArtistBulkRetrieveResponse

      def list_albums: (
        String id,
        ?include_groups: String,
        ?limit: Integer,
        ?market: String,
        ?offset: Integer,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Internal::CursorURLPage[Spotted::Models::ArtistListAlbumsResponse]

      def list_related_artists: (
        String id,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ArtistListRelatedArtistsResponse

      def top_tracks: (
        String id,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ArtistTopTracksResponse

      def initialize: (client: Spotted::Client) -> void
    end
  end
end
