module Spotted
  module Resources
    class AudioAnalysis
      def retrieve: (
        String id,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::AudioAnalysisRetrieveResponse

      def initialize: (client: Spotted::Client) -> void
    end
  end
end
