module Spotted
  module Resources
    class Audiobooks
      def retrieve: (
        String id,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::AudiobookRetrieveResponse

      def bulk_retrieve: (
        ids: String,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::AudiobookBulkRetrieveResponse

      def list_chapters: (
        String id,
        ?limit: Integer,
        ?market: String,
        ?offset: Integer,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Internal::CursorURLPage[Spotted::SimplifiedChapterObject]

      def initialize: (client: Spotted::Client) -> void
    end
  end
end
