module Spotted
  module Resources
    class Chapters
      def retrieve: (
        String id,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ChapterRetrieveResponse

      def bulk_retrieve: (
        ids: String,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::ChapterBulkRetrieveResponse

      def initialize: (client: Spotted::Client) -> void
    end
  end
end
