module Spotted
  module Resources
    class Tracks
      def retrieve: (
        String id,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::TrackObject

      def bulk_retrieve: (
        ids: String,
        ?market: String,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::TrackBulkRetrieveResponse

      def initialize: (client: Spotted::Client) -> void
    end
  end
end
