module Spotted
  module Resources
    class Users
      attr_reader playlists: Spotted::Resources::Users::Playlists

      def retrieve_profile: (
        String user_id,
        ?request_options: Spotted::request_opts
      ) -> Spotted::Models::UserRetrieveProfileResponse

      def initialize: (client: Spotted::Client) -> void
    end
  end
end
