module Spotted
  module Resources
    class Playlists
      class Images
        def list: (
          String playlist_id,
          ?request_options: Spotted::request_opts
        ) -> Spotted::Models::Playlists::image_list_response

        def initialize: (client: Spotted::Client) -> void
      end
    end
  end
end
