module Spotted
  module Models
    module Users
      type playlist_create_params =
        {
          user_id: String,
          name: String,
          collaborative: bool,
          description: String,
          published: bool
        }
        & Spotted::Internal::Type::request_parameters

      class PlaylistCreateParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_accessor user_id: String

        attr_accessor name: String

        attr_reader collaborative: bool?

        def collaborative=: (bool) -> bool

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          user_id: String,
          name: String,
          ?collaborative: bool,
          ?description: String,
          ?published: bool,
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          user_id: String,
          name: String,
          collaborative: bool,
          description: String,
          published: bool,
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
