module Spotted
  module Models
    module Playlists
      type follower_follow_params =
        { playlist_id: String, published: bool }
        & Spotted::Internal::Type::request_parameters

      class FollowerFollowParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_accessor playlist_id: String

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          playlist_id: String,
          ?published: bool,
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          playlist_id: String,
          published: bool,
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
