module Spotted
  module Models
    module Playlists
      type follower_check_params =
        { ids: String } & Spotted::Internal::Type::request_parameters

      class FollowerCheckParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_reader ids: String?

        def ids=: (String) -> String

        def initialize: (
          ?ids: String,
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          ids: String,
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
