module Spotted
  module Models
    module Playlists
      type image_retrieve_response = ::Array[Spotted::ImageObject]

      ImageRetrieveResponse: Spotted::Internal::Type::Converter
    end
  end
end
