module Spotted
  module Models
    module Playlists
      type track_add_params =
        { body_position: Integer, body_uris: ::Array[String] }
        & Spotted::Internal::Type::request_parameters

      class TrackAddParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_reader body_position: Integer?

        def body_position=: (Integer) -> Integer

        attr_reader body_uris: ::Array[String]?

        def body_uris=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?body_position: Integer,
          ?body_uris: ::Array[String],
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          body_position: Integer,
          body_uris: ::Array[String],
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
