module Spotted
  module Models
    module Playlists
      type track_add_params =
        { position: Integer, published: bool, uris: ::Array[String] }
        & Spotted::Internal::Type::request_parameters

      class TrackAddParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_reader position: Integer?

        def position=: (Integer) -> Integer

        attr_reader published: bool?

        def published=: (bool) -> bool

        attr_reader uris: ::Array[String]?

        def uris=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?position: Integer,
          ?published: bool,
          ?uris: ::Array[String],
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          position: Integer,
          published: bool,
          uris: ::Array[String],
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
