module Spotted
  module Models
    module Browse
      type category_get_playlists_response =
        { message: String, playlists: Spotted::PagingPlaylistObject }

      class CategoryGetPlaylistsResponse < Spotted::Internal::Type::BaseModel
        attr_reader message: String?

        def message=: (String) -> String

        attr_reader playlists: Spotted::PagingPlaylistObject?

        def playlists=: (
          Spotted::PagingPlaylistObject
        ) -> Spotted::PagingPlaylistObject

        def initialize: (
          ?message: String,
          ?playlists: Spotted::PagingPlaylistObject
        ) -> void

        def to_hash: -> {
          message: String,
          playlists: Spotted::PagingPlaylistObject
        }
      end
    end
  end
end
