module Spotted
  module Models
    module Browse
      type category_list_response =
        {
          id: String,
          href: String,
          icons: ::Array[Spotted::ImageObject],
          name: String,
          published: bool
        }

      class CategoryListResponse < Spotted::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor href: String

        attr_accessor icons: ::Array[Spotted::ImageObject]

        attr_accessor name: String

        attr_reader published: bool?

        def published=: (bool) -> bool

        def initialize: (
          id: String,
          href: String,
          icons: ::Array[Spotted::ImageObject],
          name: String,
          ?published: bool
        ) -> void

        def to_hash: -> {
          id: String,
          href: String,
          icons: ::Array[Spotted::ImageObject],
          name: String,
          published: bool
        }
      end
    end
  end
end
