module Spotted
  module Models
    module Browse
      type category_get_playlists_params =
        { limit: Integer, offset: Integer }
        & Spotted::Internal::Type::request_parameters

      class CategoryGetPlaylistsParams < Spotted::Internal::Type::BaseModel
        extend Spotted::Internal::Type::RequestParameters::Converter
        include Spotted::Internal::Type::RequestParameters

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader offset: Integer?

        def offset=: (Integer) -> Integer

        def initialize: (
          ?limit: Integer,
          ?offset: Integer,
          ?request_options: Spotted::request_opts
        ) -> void

        def to_hash: -> {
          limit: Integer,
          offset: Integer,
          request_options: Spotted::RequestOptions
        }
      end
    end
  end
end
